workers:
  hosts:
    worker0:
      ansible_host: worker0
    worker1:
      ansible_host: worker1
    
masters:
  hosts:
    master0:
      ansible_host: master0

kvm_host:
  hosts:
    localhost:
      ansible_host: 127.0.0.1
      username: aryanc23

kvm_cluster:
  children:
    masters:
    workers:
